name: Create Release

# Trigger whenever any tag is created
on:
  create:
    tags:
      - 'version_*'

jobs:
  create:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: true
